services:
  backend:
    build:
      context: ./services/flask_server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: main.py
      SECRET_KEY: ${SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/vusvista-db
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      FRONT_URL: http:localhost:3001
      POSTGRES_DB: vusvista-db
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vusvista-db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: http://backend:5001
      HTTPS: false
    depends_on:
      - backend

volumes:
  pgdata:
