services:
  web:
    image: espi0027/vus-curation-system:latest
    command: gunicorn -w 4 --bind 0.0.0.0:5001 main:app
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: main.py
      SECRET_KEY: 'h227GW-MI.5k}@H+Ppi"NOXO2#c)_z'
      SQLALCHEMY_DATABASE_URI: 'postgresql://vcs-postgres:ktUQNP4bp9B1Ox@db:5432/vcs-db'
      MAIL_PASSWORD: 'qzga rhqd ipiq byty'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: vcs-postgres
      POSTGRES_PASSWORD: ktUQNP4bp9B1Ox
      POSTGRES_DB: vcs-db
    ports:
      - "5433:5432"
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: